name: Discord Commits

on:
  push:
    branches:
      - master

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.8
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
